"""empty message

Revision ID: b44bdfc0df9c
Revises: 787199a98927
Create Date: 2021-03-18 12:00:30.353743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b44bdfc0df9c'
down_revision = '787199a98927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_websites',
    sa.Column('career_website_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('website', mysql.TINYTEXT(), nullable=True),
    sa.Column('username', mysql.TINYTEXT(), nullable=True),
    sa.Column('date_resume_posted', mysql.DATETIME(), nullable=True),
    sa.Column('date_cover_letter_posted', mysql.DATETIME(), nullable=True),
    sa.Column('comments', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('career_website_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('career_websites')
    # ### end Alembic commands ###
