"""empty message

Revision ID: d8759e64ae74
Revises: f85b834372c3
Create Date: 2021-03-17 12:22:22.993431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd8759e64ae74'
down_revision = 'f85b834372c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('interview_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('interview_date', mysql.DATETIME(), nullable=True),
    sa.Column('interviewer_name_and_title', mysql.TINYTEXT(), nullable=True),
    sa.Column('phone', mysql.TINYTEXT(), nullable=True),
    sa.Column('email_and_other_contact', mysql.TINYTEXT(), nullable=True),
    sa.Column('interview_address', mysql.TINYTEXT(), nullable=True),
    sa.Column('mailing_address', mysql.TINYTEXT(), nullable=True),
    sa.Column('follow_up_date', mysql.DATETIME(), nullable=True),
    sa.Column('comments', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('interview_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interviews')
    # ### end Alembic commands ###
