"""empty message

Revision ID: d987afbcddd3
Revises: d8759e64ae74
Create Date: 2021-03-18 11:20:52.214363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd987afbcddd3'
down_revision = 'd8759e64ae74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('networking_acquaintances',
    sa.Column('network_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('acquaintance_name_and_title', mysql.TINYTEXT(), nullable=True),
    sa.Column('company_name', mysql.TINYTEXT(), nullable=True),
    sa.Column('contact_information', mysql.TINYTEXT(), nullable=True),
    sa.Column('comments', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('network_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('networking_acquaintances')
    # ### end Alembic commands ###
